name: escaexplorer
on:
    push:
        branches:
            - master
jobs:
    build:
    runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v2
           - uses: akhileshns/heroku-deploy@v3.12.12
           with:
               heroku_api_key: ${{secrets.HEROKU_API_KEY}}
               heroku_app_name: "escaexplorer"
               heroku_email: ${{secrets.HEROKU_EMAIL}}
               healthcheck: "https://escaexplorer.herokuapp.com/"
               usedocker: true
               delay: 60
               rollbackonhealthcheckfailed: true
