name: shiny_app_heroku_deplo
    on:
        push:
            branches:
                - master
jobs:
    build:
    runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v2
           with:
               heroku_api_key: ${{secrets.HEROKU_API_KEY}}
               heroku_app_name: "escaexplorer"
               heroku_email: ${{secrets.HEROKU_EMAIL}}
               healthcheck: "https://geocode-shiny.herokuapp.com/"
               usedocker: true
               delay: 60
               rollbackonhealthcheckfailed: true
